name: dartchat
description: A sample web application
dependencies:
  angular: any
  browser: any
  start: any
  web_components: any

transformers:
- angular:
    html_files:
      - web/app.html
      - web/chat.html
      - web/chat_message.html
      - web/dartchat.html
      - web/footer.html
      - web/login.html
      - web/sidebar.html
#  html_files:
#    - login.html