project_metadata:
  package: promua_chat

global:
  engine.logging.on: true
  engine.sqlalchemy.on: true

controllers:
  '':
    controller: !!python/name:promua_chat.controller.Root
    /:
      tools.sessions.on: false
      tools.staticdir.root: /app/static/build/web
      tools.staticfile.root: /app/static/web
    /chat:
      tools.sessions.on: false
      tools.staticdir.on: true
      tools.staticdir.dir: .
      tools.staticdir.index: dartchat.html
    /favicon.ico:
      tools.sessions.on: false
      tools.staticfile.on: true
      tools.staticfile.filename: favicon.ico
  /api:
    controller: !!python/name:promua_chat.rest_controller.rest_api
    /:
      request.dispatch: !!python/name:promua_chat.rest_controller.rest_api
      tools.sessions.on: true
      tools.orm_session.on: true

sqlalchemy_engine:
  url: postgres://mnmiwvalcdbdju:Mp1TuEZeHXXon0de1PZSrIwjKu@ec2-54-247-78-153.eu-west-1.compute.amazonaws.com:5432/d7683oe93f51ja
  pool_recycle: 3600

jinja2:
  loader: !!python/object:jinja2.loaders.FileSystemLoader
          encoding: utf-8
          searchpath: [/app/src/promua_chat/templates]
  bytecode_cache: !!python/object:jinja2.bccache.FileSystemBytecodeCache {directory: /app/.cache,
                                                                          pattern: __jinja2_%s.cache}
  auto_reload: true
  use_webassets: true
